apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keratin-authn-server.fullname" . }}
  labels:
    {{- include "keratin-authn-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keratin-authn-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keratin-authn-server.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "keratin-authn-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.publicPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            - name: AUTHN_URL
              value: {{ .Values.authnUrl }}
            - name: APP_DOMAINS
              value: {{ .Values.appDomains }}
            - name: HTTP_AUTH_USERNAME
              value: {{ .Values.httpAuthUsername }}
            - name: HTTP_AUTH_PASSWORD
              value: {{ .Values.httpAuthPassword }}
            - name: SECRET_KEY_BASE
              value: {{ .Values.secretKeyBase }}
            - name: DATABASE_URL
              value: {{ .Values.databaseUrl }}
            - name: REDIS_URL
              value: {{ .Values.redisUrl }}
            - name: PORT
              value: "{{ .Values.port }}"
            - name: PUBLIC_PORT
              value: "{{ .Values.publicPort }}"
            - name: SENTRY_DSN
              value: "{{ .Values.sentryDsn }}"
            - name: FACEBOOK_OAUTH_CREDENTIALS
              value: "{{ .Values.facebook.appId }}:{{ .Values.facebook.appSecret }}"

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-redis
          image: redis:5.0.5-alpine
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
