apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keratin-authn-server.fullname" . }}
  labels:
    {{- include "keratin-authn-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keratin-authn-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "keratin-authn-server.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
              httpHeaders:
                - name: Host
                  value:  {{ .Values.authnUrl }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
              httpHeaders:
                - name: Host
                  value:  {{ .Values.authnUrl }}
         
          env:
            - name: AUTHN_URL
              value: {{ .Values.appSettings.authnUrl }}
            - name: APP_DOMAINS
              value: {{ .Values.appSettings.appDomains }}
            - name: PUBLIC_PORT
              value: {{ .Values.appSettings.publicPort }}

            - name: HTTP_AUTH_USERNAME
              value: {{ .Values.internalApi.username }}
            - name: HTTP_AUTH_PASSWORD
              value: {{ .Values.internalApi.password }}
            - name: PORT
              value: {{ .Values.internalApi.port }}

            - name: SECRET_KEY_BASE
              value: {{ .Values.secretKeyBase }}
            
            - name: DATABASE_URL
              value: {{ .Values.persistence.databaseUrl }}
            - name: REDIS_URL
              value: {{ include "redis.masterConnectString" . | quote }} 
              # value: {{ .Values.persistence.redisUrl }}

            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
