apiVersion: v1
kind: Service
metadata:
  name: {{ include "keratin-authn-server.fullname" . }}
  labels:
    {{- include "keratin-authn-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.internal }}
      targetPort: internal
      protocol: TCP
      name: internal
  selector:
    {{- include "keratin-authn-server.selectorLabels" . | nindent 4 }}
