apiVersion: v2
name: keratin-authn-server
description: Ready to use authn microservice

type: application
version: 0.1.0
appVersion: 1.7.0

dependencies:
  - name: redis
    version: 10.4.x
    repository: https://charts.bitnami.com
    condition: redis.enabled
    tags:
      - keratin-authn-server
  
  - name: mariadb
    version: 7.x.x
    repository: https://charts.bitnami.com
    condition: mariadb.enabled
    tags:
      - keratin-authn-server