apiVersion: v2
name: keratin-authn-server
description: Ready to use authn microservice
home: https://keratin.tech
icon: https://keratin.tech/pangolin-logo-dark.gif

type: application
version: 0.2.2
appVersion: 1.8.0
maintainers:
  - email: a.a.obukhov@gmail.com
    name: Aleks Obukhov
  
dependencies:
  - name: redis
    version: 10.4.x
    repository: https://charts.bitnami.com
    condition: redis.enabled
    tags:
      - keratin-authn-server
  
  - name: mariadb
    version: 7.x.x
    repository: https://charts.bitnami.com
    condition: mariadb.enabled
    tags:
      - keratin-authn-server